###
### Requêtes pour l'API de Suivi de Projets de Recherche
###

# GET - Récupérer tous les projets de recherche
GET http://127.0.0.1:8000/api/projets/
Content-Type: application/json

###

# POST - Créer un nouveau projet de recherche
POST http://127.0.0.1:8000/api/projets/
Content-Type: application/json

{
  "titre": "Nouveau projet",
  "description": "Description du nouveau projet",
  "date_debut": "2024-07-01",
  "date_fin_prevue": "2025-01-01",
  "chef_de_projet": 1
}

###

# GET - Récupérer tous les chercheurs
GET http://127.0.0.1:8000/api/chercheurs/
Content-Type: application/json

###

# POST - Créer un nouveau chercheur
POST http://127.0.0.1:8000/api/chercheurs/
Content-Type: application/json

{
  "nom": "John Doe",
  "specialite": "Biologie moléculaire"
}

###
# Test de la mise à jour d'un chercheur
PUT http://127.0.0.1:8000/chercheurs/update/1/
Content-Type: application/json

{
    "nom": "updated chercheur",
    "specialte": "updated specialite",
}

###
DELETE http://127.0.0.1:8000/chercheurs/1/delete/
Content-Type: application/json

###

###
# GET - Récupérer toutes les publications
GET http://127.0.0.1:8000/api/publications/
Content-Type: application/json

###

# POST - Créer une nouvelle publication
POST http://127.0.0.1:8000/api/publications/
Content-Type: application/json

{
  "titre": "Nouvelle publication",
  "resume": "Résumé de la nouvelle publication",
  "projet_associé": 1,
  "date_publication": "2024-06-26"
}
