# Generated by Django 5.0.6 on 2024-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='projet',
            new_name='projet_associe',
        ),
        migrations.AddField(
            model_name='chercheur',
            name='projets',
            field=models.ManyToManyField(related_name='chercheurs_associes', to='api.projetderecherche'),
        ),
        migrations.AlterField(
            model_name='projetderecherche',
            name='chercheurs',
            field=models.ManyToManyField(related_name='projets_associes', to='api.chercheur'),
        ),
    ]
