# Generated by Django 5.0.6 on 2024-06-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_projet_publication_projet_associe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetderecherche',
            name='chercheurs',
        ),
        migrations.AlterField(
            model_name='chercheur',
            name='projets',
            field=models.ManyToManyField(blank=True, related_name='chercheurs_associes', to='api.projetderecherche'),
        ),
    ]
